CREATE TABLE Files (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    doc_id INT UNSIGNED NOT NULL,
    filename VARCHAR(100) NOT NULL,
    guid VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE Files DROP COLUMN doc_id;
ALTER TABLE Files DROP COLUMN created_at;
ALTER TABLE Files DROP COLUMN updated_at;
